[general]
name = "soundsphere 7key o2tiles noteskin toml"
inputMode = "7key"
input = [
	"key1",
	"key2",
	"key3",
	"key4",
	"key5",
	"key6",
	"key7"
]
unit = 600
scroll = 1

[columns]
x = 0
y = 480
width = [28, 22, 28, 32, 28, 22, 28]
height = [7, 7, 7, 7, 7, 7, 7]
space = [0, 0, 0, 0, 0, 0, 0, 0]

[measureline]
height = 1
layer = 0
image = "pixel.png"

[score]
[score.score]
format = "%07d\n "
align = ["center", "bottom"]
color = [255, 255, 255, 255]
font = "resources/fonts/SourceCodePro-Semibold.ttf"
size = 28
[score.accuracy]
format = "%0.2f"
align = ["center", "bottom"]
color = [255, 255, 255, 255]
font = "resources/fonts/SourceCodePro-Regular.ttf"
size = 22
[score.combo]
format = "%d"
align = ["center", "center"]
color = [255, 255, 255, 127]
font = "resources/fonts/SourceCodePro-Bold.ttf"
size = 160
[score.timegate]
format = "%s"
align = ["center", "center"]
color = [255, 255, 255, 255]
font = "resources/fonts/SourceCodePro-Regular.ttf"
size = 28

[keys]
padding = 0
width = [28, 22, 28, 32, 28, 22, 28]
height = [600, 600, 600, 600, 600, 600, 600, 600]
layer = 4
pressed = [
	"key1-1.png",
	"key2-1.png",
	"key1-1.png",
	"key4-1.png",
	"key1-1.png",
	"key2-1.png",
	"key1-1.png"
]
released = [
	"key1-0.png",
	"key2-0.png",
	"key1-0.png",
	"key4-0.png",
	"key1-0.png",
	"key2-0.png",
	"key1-0.png"
]

[notes]
[notes.ShortNote]
[notes.ShortNote.Head]
layer = 3
images = [
	"white.png",
	"blue.png",
	"white.png",
	"yellow.png",
	"white.png",
	"blue.png",
	"white.png"
]
[notes.LongNote]
[notes.LongNote.Head]
layer = 3
images = [
	"white.png",
	"blue.png",
	"white.png",
	"yellow.png",
	"white.png",
	"blue.png",
	"white.png"
]
[notes.LongNote.Body]
layer = 1
images = [
	"white.png",
	"blue.png",
	"white.png",
	"yellow.png",
	"white.png",
	"blue.png",
	"white.png"
]
[notes.LongNote.Tail]
layer = 2
images = [
	"white.png",
	"blue.png",
	"white.png",
	"yellow.png",
	"white.png",
	"blue.png",
	"white.png"
]