[general]
name = "soundsphere 4key arrow noteskin toml"
inputMode = "4key"
input = ["key1", "key2", "key3", "key4"]
unit = 480
scroll = -1

[columns]
x = 0
y = 450
width = [64, 64, 64, 64]
height = [64, 64, 64, 64]
space = [32, 0, 0, 0, 32]

[measureline]
height = 2
layer = 0
image = "pixel.png"

[score]
[score.score]
format = "%07d"
align = ["right", "top"]
color = [255, 255, 255, 255]
font = "resources/fonts/SourceCodePro-Semibold.ttf"
size = 40
[score.accuracy]
format = "\n%0.2f"
align = ["right", "top"]
color = [255, 255, 255, 255]
font = "resources/fonts/SourceCodePro-Regular.ttf"
size = 32
[score.combo]
format = "%d"
align = ["center", "center"]
color = [255, 255, 255, 95]
font = "resources/fonts/SourceCodePro-Bold.ttf"
size = 240
[score.timegate]
format = "%s"
align = ["center", "center"]
color = [255, 255, 255, 255]
font = "resources/fonts/SourceCodePro-Regular.ttf"
size = 28

[keys]
padding = 30
width = [64, 64, 64, 64]
height = [64, 64, 64, 64]
layer = 4
pressed = ["key/left1.png", "key/down1.png", "key/up1.png", "key/right1.png"]
released = ["key/left0.png", "key/down0.png", "key/up0.png", "key/right0.png"]

[notes]
[notes.ShortNote]
[notes.ShortNote.Head]
layer = 3
images = ["note/left.png", "note/down.png", "note/up.png", "note/right.png"]
[notes.LongNote]
[notes.LongNote.Head]
layer = 3
images = ["note/left.png", "note/down.png", "note/up.png", "note/right.png"]
[notes.LongNote.Body]
layer = 1
images = ["note/body.png", "note/body.png", "note/body.png", "note/body.png"]
[notes.LongNote.Tail]
layer = 2
images = ["note/tail-down.png", "note/tail-down.png", "note/tail-down.png", "note/tail-down.png"]