[general]
name = "soundsphere 4key arrow2 noteskin toml"
inputMode = "4key"
input = ["key1", "key2", "key3", "key4"]
unit = 480
scroll = 1

[columns]
x = 0
y = 450
width = [64, 64, 64, 64]
height = [64, 64, 64, 64]
space = [32, 0, 0, 0, 32]

[measureline]
height = 2
layer = 0
image = "pixel.png"

[score]
[score.score]
format = "%07d"
align = ["right", "top"]
color = [255, 255, 255, 255]
font = "resources/fonts/SourceCodePro-Semibold.ttf"
size = 40
[score.accuracy]
format = "\n%0.2f"
align = ["right", "top"]
color = [255, 255, 255, 255]
font = "resources/fonts/SourceCodePro-Regular.ttf"
size = 32
[score.combo]
format = "%d"
align = ["center", "center"]
color = [255, 255, 255, 95]
font = "resources/fonts/SourceCodePro-Bold.ttf"
size = 240
[score.timegate]
format = "%s"
align = ["center", "center"]
color = [255, 255, 255, 255]
font = "resources/fonts/SourceCodePro-Regular.ttf"
size = 28

[keys]
padding = 30
width = [64, 64, 64, 64]
height = [64, 64, 64, 64]
layer = 4
pressed = ["key2/left1.png", "key2/down1.png", "key2/up1.png", "key2/right1.png"]
released = ["key2/left0.png", "key2/down0.png", "key2/up0.png", "key2/right0.png"]

[notes]
[notes.ShortNote]
[notes.ShortNote.Head]
layer = 3
images = ["note2/left.png", "note2/down.png", "note2/up.png", "note2/right.png"]
[notes.LongNote]
[notes.LongNote.Head]
layer = 3
images = ["note2/left.png", "note2/down.png", "note2/up.png", "note2/right.png"]
[notes.LongNote.Body]
layer = 1
images = ["note2/body.png", "note2/body.png", "note2/body.png", "note2/body.png"]
[notes.LongNote.Tail]
layer = 2
images = ["note2/tail.png", "note2/tail.png", "note2/tail.png", "note2/tail.png"]